apiVersion: v1
kind: ConfigMap
metadata:
  name: recruiterreply-backend-config
  namespace: recruiterreply-dev
data:
  ASPNETCORE_ENVIRONMENT: Development
  Database__AutoCreateSchema: "false"
  Jwt__Issuer: RecruiterReply
  Jwt__Audience: RecruiterReply.Client
