apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: recruiterreply-dev
  namespace: recruiterreply-dev
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/success-codes: "200-399"
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: recruiterreply-backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: recruiterreply-frontend
                port:
                  number: 80
